# #####################################################################
# Automatically generated by qmake (2.01a) Fri Jun 4 11:29:03 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    src \
    src/core \
    src/gui \
    src/gui/forms
INCLUDEPATH += . \
    src/gui \
    src/core

# Input
HEADERS += src/core/cpd.h \
    src/core/mix.h \
    src/core/step.h \
    src/gui/cpdwindow.h \
    src/gui/mainwindow.h \
    src/gui/stepwindow.h \
    src/gui/newcpddialog.h
FORMS += src/gui/forms/cpd.ui \
    src/gui/forms/main.ui \
    src/gui/forms/step.ui \
    src/gui/forms/newcpddialog.ui
SOURCES += src/chemecher.cpp \
    src/core/cpd.cpp \
    src/core/mix.cpp \
    src/core/step.cpp \
    src/gui/cpdwindow.cpp \
    src/gui/mainwindow.cpp \
    src/gui/stepwindow.cpp \
    src/gui/newcpddialog.cpp
