# #####################################################################
# Automatically generated by qmake (2.01a) Fri Jun 4 11:29:03 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    src \
    src/core
INCLUDEPATH += . \
    src/core
QT += sql \
    xml

# Input
HEADERS += src/core/cpd.h \
    src/core/mix.h \
    src/core/step.h \
    src/core/dbhandler.h \
    src/core/iomanager.h 
SOURCES += src/chemecher-cli.cpp \
    src/core/cpd.cpp \
    src/core/mix.cpp \
    src/core/step.cpp \
    src/core/dbhandler.cpp \
    src/core/iomanager.cpp 
