#include "iomanager.h"

IOManager *iomgr = new IOManager();

IOManager::IOManager()
{

}

bool IOManager::saveToCM3(QString sim, QString mech)
{
	//open the mechanism file
	QFile mfile(mech);
	if( !mfile.open( QFile::WriteOnly ) ){
		status = FS_ERROR;
		message = "Error opening file "+mech;
		return false;
	}

	/***************** write to the mechanism file *****************/

	QTextStream mOut( &mfile );
	mOut << "'Generated by CheMecher v4 on ";
	mOut << QDateTime::currentDateTime().toString("ddd MMMM d yyyy hh:mm ap") << endl;
	mOut << "'Name: " + (mix->mechName.isEmpty() ? "<empty>" : mix->mechName) << endl;
	mOut << "'Desc: " + (mix->mechDesc.isEmpty() ? "<empty>" : mix->mechDesc) << endl;

	//write out the cpd list
	mOut << "'the list of compounds" << endl;
	mOut << mix->CpdList.size() << endl;
	for(int i=0; i<mix->CpdList.size(); i++)
		mOut << mix->CpdList[i]->tov3String() << endl;
	mOut << endl;

	//write out the step list
	mOut << "'the list of steps" << endl;
	mOut << mix->StepList.size() << endl;
	for(int i=0; i<mix->StepList.size(); i++)
		mOut << mix->StepList[i]->tov3String() << endl;
	mOut << endl;

	mfile.close();
}

bool IOManager::loadFromCM3(QString sim, QString mech)
{
	sim; mech;
	return false;
}

bool IOManager::saveToCM4(QString filename)
{
	filename;
	return false;
}

bool IOManager::loadFromCM4(QString filename)
{
	filename;
	return false;
}
